require("../app")
let { Router } = require("express")
const router = Router()
const passport = require("passport");

const {view_marksheet,view_eventt, fetchUserFromGoogle, 
  attendance_marked} = require("../controllers/normalController")

const {authenticateToken,admin_student,} = require("../middleware/authentication")

 
/*This route is for getting marksheets of a student by putting studentId in params */
router.get("/viewmarksheet/:studentId",authenticateToken,admin_student,view_marksheet);


/* You can view events by putting date in params make sure the date format YYYY-MM-DD*/
router.get("/viewevents/:day",authenticateToken,view_eventt);

/*This route for guest only the didnt need to login just the can do a third party login. 
  Guest can only see events details(view events route)*/
router.get(
    "/google",
    passport.authenticate("google", {
      session: false,
      scope: ["profile", "email"]
    })
  );

  /*Gooogle will redirect you to this you will get your token as json use that for login */
router.get("/google/redirect",passport.authenticate('google',{
    session:false,
    failureRedirect:"http://localhost:1234/#login"
}),
fetchUserFromGoogle);

/*This route is for marking your attendance via LINK Generated by professors just put that link in postman 
along with your authorization BEARER token */
router.get("/attendance/:token",authenticateToken,admin_student,attendance_marked)







module.exports = router;